### ISSUE TITLE
Erstellung von Testdaten

### ISSUE THREAD

**Issue by IlOblomov** [AstralJaeger/NextStop-SWK-2024#10]
Erstellung von Testdaten für Feiertage und Schulferien (für die Jahre 2024 und 2025), Routen (mind. 3) und Haltestellen (ca. 10 pro Route). Bei Gruppenarbeit müssen sich Routen zum Teil überschneiden, damit Fahrplanabfragen mit Umstieg getestet werden können.

**Comment by AstralJaeger** [comment]
Open ToDo's:
- [ ] Testdaten von Linz AG erstellen
- [ ] UnitTests für bestehenden Code erstellen
